  tasks: 
  - name: aws-cli
    env: 
    AWS_CLI_AUTO_PROMT: on-partial
    init: |
  cd /workplace
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  unzip awscliv2.zip
  sudo ./aws/install
  cd $THEIA_WORKPLACE_ROOT
  vscode:
    extensions:
    - 42Crunch.vscode-openapi
